# Generated by Django 4.2 on 2023-05-01 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.RenameField(
            model_name="paymentrequest",
            old_name="timestamp",
            new_name="date",
        ),
        migrations.AddField(
            model_name="account",
            name="currency",
            field=models.CharField(
                choices=[("GBP", "Pounds"), ("USD", "US Dollars"), ("EUR", "Euros")],
                default="GBP",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="conversion_rate",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="paymentrequest",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_payment_requests",
                to="payapp.account",
            ),
        ),
        migrations.AlterField(
            model_name="paymentrequest",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_payment_requests",
                to="payapp.account",
            ),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
