# Generated by Django 4.2 on 2023-05-01 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payapp", "0003_alter_paymentrequest_receiver_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentrequest",
            old_name="sender",
            new_name="from_account",
        ),
        migrations.RenameField(
            model_name="paymentrequest",
            old_name="receiver",
            new_name="to_account",
        ),
    ]
