# Generated by Django 4.2 on 2023-05-01 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payapp", "0004_rename_sender_paymentrequest_from_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_request",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="payment_request",
                to="payapp.paymentrequest",
            ),
        ),
    ]
