# Generated by Django 4.2 on 2023-05-02 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payapp", "0005_transaction_payment_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="payment_request",
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="transaction",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="transaction",
                to="payapp.transaction",
            ),
        ),
    ]
